### ISSUE TITLE
Organize code in different scripts

### ISSUE THREAD

**Issue by wlord01** [wlord01/GiovanniIlariaWilliam#5]
It is probably a good idea to organize the code in different scripts for better overview and for easier testing/running. We can follow the guidelines [here](http://intermediate-and-advanced-software-carpentry.readthedocs.io/en/latest/structuring-python.html) and [here](https://www.python.org/dev/peps/pep-0008/) (The links I already sent you on WhatsApp). For example:
* Put classes in a separate package/modules and import to main script
* Put much of the code in the main script into functions
* Test our code using "if \_\_name\_\_ == '\_\_main\_\_':"

**Comment by mefit0** [comment]
Well done! 
Nice idea; as you said, we should do the same with the animation and initialization of the variables/objects so that we'll have in the end just a "clean" script for the "running" script. 
Maybe we should also insert the method "pixelLoop" in the class Retina so that we can get rid of it from the main script, at least until we'll decide to try the other method with the pixels represented by a dot instead that by the square.

I didn't really get instead what you mean with:

> Test our code using "if __name__ == '__main__':"

Are you @wlord01  referring to the compare between the external environment and the goal or..? :)

**Comment by wlord01** [comment]
* Thank you :) Right, we could possibly put the pixelLoop function inside Retina. Another option would be to put it with other functions in the top of the main script or in a separate functions file. But this particular one might sit best inside Retina(?). 

* So @mefit0, by "test our code using "if \_\_name\_\_ == '\_\_main\_\_':"" i meant that this can be put in a script to run different tests, as described [here](http://intermediate-and-advanced-software-carpentry.readthedocs.io/en/latest/structuring-python.html). This line of code makes the difference that if you run the script then whatever is inside this if-statement will run, but if you import the script then only the defined functions/classes/methods will be imported and what is in the if-statement will not run.

**Comment by wlord01** [comment]
So far we have moved the classes into a package. To organize the structure further we could move other functions and code out from the main script. @mefit0 do you want to do this?

- [x] Move classes of polygon objects out from main script and into package 'polygonobjects'
- [x] Move pixelLoop out from the main script into the Retina class (?)
- [x] Move other code from main script (?)

**Comment by mefit0** [comment]
> we could possibly put the pixelLoop function inside Retina.
>  @mefit0 do you want to do this?

I'm going to do this ;)

> i meant that this can be put in a script to run different tests

now it's clear, thank you! As soon as i can i'll read the link you suggest about the structuring ;)

**Comment by mefit0** [comment]
I've uploaded all the new scripts and modifications. Sorry if i maybe made a mess creating a lot of new branches but i thought that it was better so for you to check them (instead of just merge with the master branch .. but maybe i'm wrong, i'm still trying to understand how github works XD). I had:

- Updated the init/class script with the pixelLoop function in the class Retina.

- Added the script with the initialization of variables and objects.

- Added the script for the plot.

- Modified the main script so that it contains only the "run" and the option of plot yes/no (for now i've just used the "if graphic == "on" .. import animation script").

**Comment by wlord01** [comment]
Hey, nice work! :)

Yes this is exactly how GitHub works, one commits in a separate branch instead of the master to let others review the work before it is merged into the main branch (master). However, you created four branches now, of which one (the ini-script creation) seems to be closed, while in my opinion all these could have been in one branch called something like "structuring-code-and-scripts". In this branch the different commits could be added, and all the changes (created files and moved code) would show in one pull request, which I think would be more clear.

I don't know if you want to try and do this or if this makes things complicated and instead we'll just treat the different pull requests for now (this would work too)?

**Comment by mefit0** [comment]
yes, i agree! i was trying to do something like that (single branch with different scripts inside) but i wasn't able to do that .. if you can do that, it would be perfect in my opinion :)

**Comment by wlord01** [comment]
All right! So for that you just need to do all the changes and commit in one single branch. Then you create a pull request from that branch so all the changes are in one package so to speak :) But I can definitely do it this time if you want?
